### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by fgiarritiello** [NexxLuo/tablex#1]
I'm getting this error when importing the library and building the project

node_modules/react-beautiful-dnd/node_modules/react-redux/es/components/Provider.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in '/node_modules/react-beautiful-dnd/node_modules/react-redux/es/components'

any ideas?

**Comment by NexxLuo** [comment]
Perhaps the reason is the package.json missing the react-beautiful-dnd dependence ,you can add it.
Soon afterwards,i will remove this dependence.

**Comment by NexxLuo** [comment]
I have removed the dependence .
