### ISSUE TITLE
ts声明文件不完善

### ISSUE THREAD

**Issue by ghost** [NexxLuo/tablex#14]
缺少oncell,intl等配置项，不过是可以用的，就是有点尴尬，ts报错找不到

**Comment by NexxLuo** [comment]
还缺失哪些，一并加上

**Comment by ghost** [comment]
等我下午适配完哈目前暂时发现这些，感谢感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nexx"<notifications@github.com&gt;; 
发送时间: 2020年4月29日(星期三) 中午11:13
收件人: "NexxLuo/tablex"<tablex@noreply.github.com&gt;; 
抄送: "1370336125"<1370336125@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [NexxLuo/tablex] ts声明文件不完善 (#14)





 
还缺失哪些，一并加上

**Comment by ghost** [comment]
目前发现的，onCell，intl，sortable，ref，还有rowClassName的类型，intl有个bug，如果设定了其中一个的值就会将其他默认值全部置空

**Comment by ghost** [comment]
对了，className的定义也没有

**Comment by NexxLuo** [comment]
已作处理 91ae99598d62d64b2218ee5fc387371ec603459c
