### ISSUE TITLE
表格自适应宽度bug?

### ISSUE THREAD

**Issue by condorheroblog** [NexxLuo/tablex#15]
1. 官网上讲，表格如果不设置宽度，列宽将会自动占满剩余宽度，但此时列会撕裂，怎么解决？

![image](https://user-images.githubusercontent.com/47056890/82896602-d10ed400-9f88-11ea-8817-224d26d09e77.png)

2. 怎么实现无限滚动加载，例如表格滚动到底部给个 loading 图，去请求数据，拿到表格的数据接着加载。请问有这个事件或实现思路吗？

**Comment by condorheroblog** [comment]
@NexxLuo 我在 Firefox 上使用你的插件宽度自适应的时候没有出现列撕开的 bug，表头会很好的对齐，如下图：
![表头对齐](https://user-images.githubusercontent.com/47056890/82973366-b6c90a80-a009-11ea-9c39-92c74bdef6f3.png)

Any suggestions would be greatly appreciated!

**Comment by NexxLuo** [comment]
这个问题应该是出现纵向滚动条的时候才会有。把具体的columns发下，这边尝试复现下；
无限加载暂时没有提供相关事件，或许可以通过添加滚动事件监听进行处理

**Comment by condorheroblog** [comment]
```
import ReactDOM from "react-dom";
import React from "react";
import Table from "tablex";


class Demo extends React.Component {
	generateData(columns, count = 10000, prefix = 'Row') {
		return new Array(count).fill(0).map((row, rowIndex) => {
			return columns.reduce(
				(rowData, column, columnIndex) => {
					if (column.dataIndex !== 'id') {
						rowData[column.dataIndex] = Math.floor(Math.random() * 100 + 1)
					} else {
						rowData[column.dataIndex] =
							prefix + ' ' + rowIndex + ' - Col ' + columnIndex
					}
					return rowData
				},
				{
					id: prefix + rowIndex,
					parentId: null,
				},
			)
		})
	}
	constructor(props) {
		super(props)
		const columns = [
			{
				dataIndex: 'column-1',
				key: 'column-1',
				title: 'column-1',
			},

			{
				dataIndex: 'column-2',
				key: 'column-2',
				title: 'column-2',
				width: 150,
			},

			{
				dataIndex: 'column-3',
				key: 'column-3',
				title: 'column-3',
			},
			{
				dataIndex: 'column-4',
				key: 'column-4',
				title: 'column-4',
			},
			{
				dataIndex: 'column-5',
				key: 'column-5',
				title: 'column-5',
			},
		]

		let data = this.generateData(columns, 10000)

		this.state = {
			data: data,
			columns: columns,
		}
	}
	render() {
		let { columns, data } = this.state;
		return <Table rowKey="id" columns={columns} data={data} />
	}
}


ReactDOM.render(
	<React.Fragment>
		<div style={{
			width: "1200px",
			height: "80vh",
		}}>
			<Demo />
		</div>
	</React.Fragment>
, document.getElementById("root"));
```

**Comment by condorheroblog** [comment]
@NexxLuo 
这是谷歌和Firefox的演示效果。
![image](https://user-images.githubusercontent.com/47056890/82974917-a87ced80-a00d-11ea-8a80-84e1f82a346e.png)

**Comment by shuozhang2016** [comment]
@NexxLuo 列的数量少就会出现这个问题。 列数多了就没问题了

**Comment by NexxLuo** [comment]
> </React.Fragment>

在google浏览器中未复现问题

**Comment by NexxLuo** [comment]
@condorheroblog  看下tablex 依赖的`react-base-datagrid`版本是否正确，本地环境是否依赖不正确。
也可以尝试在https://tablex.now.sh/packages/website 中进行代码实时编辑查看效果

**Comment by condorheroblog** [comment]
@NexxLuo 
现在列确实可以对齐了，但是Chrome和火狐最后一列的表现仍然不同，火狐的表现可能更加符合预期。
![image](https://user-images.githubusercontent.com/47056890/83137168-46aaa980-a11b-11ea-8f51-0fdf45b82133.png)
期待你的回复。
