### ISSUE TITLE
webpack dev报错

### ISSUE THREAD

**Issue by andyyxw** [NexxLuo/tablex#3]
引入 `tablex` 后 `webpack dev` 报错无法正常启动：

![error](https://user-images.githubusercontent.com/41931722/68067130-adcad000-fd7d-11e9-8035-a4eabb4af245.png)

**Comment by NexxLuo** [comment]
> 引入 `tablex` 后 `webpack dev` 报错无法正常启动：
> 
> ![error](https://user-images.githubusercontent.com/41931722/68067130-adcad000-fd7d-11e9-8035-a4eabb4af245.png)

这看起来更像是本地环境配置的问题

**Comment by andyyxw** [comment]
> 这看起来更像是本地环境配置的问题

打扰了，确实是我webpack loader的问题。
