### ISSUE TITLE
可以实现自动换行吗

### ISSUE THREAD

**Issue by andyyxw** [NexxLuo/tablex#4]
请问`tablex`可以实现自动换行功能吗，翻了遍文档没找到。
现在很多虚拟滚动的`Table`都不能自动换行，都是自动省略的，但是有些需求列内容要完全显示，不能省略。

**Comment by NexxLuo** [comment]
无法像普通table那样自动换行，但是可以通过动态行高进行处理。

**Comment by NexxLuo** [comment]
`v1.12.5`版本添加了新的`autoRowHeight`属性以支持自动行高
