### ISSUE TITLE
能否支持服务端排序

### ISSUE THREAD

**Issue by andyyxw** [NexxLuo/tablex#5]
目前`tablex`的排序是纯前端的，外界无法干预，但是在有分页的情况下需要服务端配合对所有数据排序，然后前端重新分页。
能否提供类似`antd`的服务端(外部)排序功能？
![sorter](https://user-images.githubusercontent.com/41931722/68369119-835d8600-0174-11ea-8fee-2f26ddc82a5e.png)
![onChange](https://user-images.githubusercontent.com/41931722/68369125-89536700-0174-11ea-8b65-e0f48c8c76eb.png)

**Comment by NexxLuo** [comment]
已添加 `onSort`事件，可在此事件中处理服务端排序
