### ISSUE TITLE
已有antd的项目样式重复

### ISSUE THREAD

**Issue by andyyxw** [NexxLuo/tablex#6]
目前`tablex`内部组件直接引用`antd.css`，所以我的项目里出现了2份`antd`的样式，并且由于`antd`版本不一致导致部分样式错乱。
请问有什么好的解决办法？（目前想到的是`tablex`内部组件不要去引`antd.css`，让使用者在自己的项目里去引入）

**Comment by NexxLuo** [comment]
内部对antd的依赖并不多，周末我尝试下移除对antd的依赖

**Comment by andyyxw** [comment]
OK，辛苦！

**Comment by NexxLuo** [comment]
`1.9.7`移除了对antd.css的import
